In [1]:
import tensorflow as tf

In [4]:
x_data = [[73.,80.,75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.],[185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X,W)+b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step%200 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        


0 Cost:  2112.18 
Prediction:
 [[ 110.72614288]
 [ 135.65472412]
 [ 132.41201782]
 [ 143.29734802]
 [ 104.84853363]]
200 Cost:  0.183217 
Prediction:
 [[ 151.50915527]
 [ 184.66183472]
 [ 180.70521545]
 [ 195.88780212]
 [ 142.22557068]]
400 Cost:  0.182499 
Prediction:
 [[ 151.51461792]
 [ 184.65800476]
 [ 180.70677185]
 [ 195.88987732]
 [ 142.21974182]]
600 Cost:  0.181835 
Prediction:
 [[ 151.51977539]
 [ 184.65438843]
 [ 180.70820618]
 [ 195.89190674]
 [ 142.21417236]]
800 Cost:  0.181245 
Prediction:
 [[ 151.52462769]
 [ 184.6509552 ]
 [ 180.70957947]
 [ 195.89381409]
 [ 142.20889282]]
1000 Cost:  0.180701 
Prediction:
 [[ 151.52920532]
 [ 184.64768982]
 [ 180.71084595]
 [ 195.89567566]
 [ 142.20384216]]
1200 Cost:  0.180199 
Prediction:
 [[ 151.53353882]
 [ 184.64466858]
 [ 180.71205139]
 [ 195.89750671]
 [ 142.19906616]]
1400 Cost:  0.179748 
Prediction:
 [[ 151.53761292]
 [ 184.64176941]
 [ 180.71318054]
 [ 195.89924622]
 [ 142.19450378]]
1600 Cost:  0.179326 
Prediction:
 [[ 15